#index:
#    path: /
#    controller: App\Controller\DefaultController::index


# config/routes.yaml

# the "app_home_number" route name is not important yet
app_home_number:
  path: /home/number
  controller: App\Controller\HomeController::number